blank_issues_enabled: false
contact_links:
  - name: Questions about this project
    url: https://github.com/Suman-jha-simform/skills-expand-your-team-with-copilot/discussions
    about: Please ask and answer general questions in Discussions.

